batch_size: 16
pretrained_model_path: ""

train:
    epochs: 400000
    log_interval: 1000
    eval_interval: 5000
    sampling_interval: 5000
    saving_interval: 100000

data:
  height: 32
  width: 32
  channel: 3
  horizontal_flip_rate: 0.5

sampling:
  n_img: 50
  save_n_row: 10

evaluate:
  n_img: 128
  timesteps: 1000
  n_surroundings: 100
  sigma: 0.05
  n_blocks: 1
