batch_size: 256
pretrained_model_path: "20241211_150912/models/epoch_001499.pth"

train:
    epochs: 1500
    log_interval: 10
    eval_interval: 50
    sampling_interval: 50
    saving_interval: 500

data:
  height: 32
  width: 32
  channel: 3
  horizontal_flip_rate: 0.5

sampling:
  n_img: 50
  save_n_row: 10

evaluate:
  n_img: 100000
  timesteps: 1
  n_surroundings: 1
  sigma: 0.05
  n_blocks: 1

